name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            suffix: windows
            exe: SyntonicDentiforms.exe
          - os: macos-latest
            suffix: mac
            exe: SyntonicDentiforms
          - os: ubuntu-latest
            suffix: linux
            exe: SyntonicDentiforms
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Download sokol-shdc (linux/mac)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p tools/bin
          if [ "${{ runner.os }}" = "Linux" ]; then
            URL="https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/linux/sokol-shdc"
          else
            URL="https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/osx/sokol-shdc"
          fi
          OUT="tools/sokol-shdc"
          curl -L -o "$OUT" "$URL"
          chmod +x "$OUT"      
      - name: Download sokol-shdc (win)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Invoke-WebRequest `
            -Uri "https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/win32/sokol-shdc.exe" `
            -OutFile "tools/sokol-shdc.exe"          

      - name: prepare-linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --clean-first
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --clean-first
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SyntonicDentiforms-${{matrix.suffix}}
          path: |
            ${{matrix.exe}}
            readme.txt
            data/
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-ninja
        run: |
          sudo apt-get update && sudo apt-get install -y ninja-build
      - name: prepare emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install 5.0.5
          ./emsdk activate 5.0.5
          cd ..
      - name: Download sokol-shdc
        run: |
          mkdir -p tools/bin
          URL="https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/linux/sokol-shdc"
          OUT="tools/sokol-shdc"
          curl -L -o "$OUT" "$URL"
          chmod +x "$OUT"      
      - name: build
        run: |
          source emsdk/emsdk_env.sh
          cmake --preset emscripten-release
          cmake --build --preset em-release
