name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            suffix: windows
            exe: SyntonicDentiforms.exe
            shdc_url: https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/win32/sokol-shdc.exe
            shdc_out: tools/sokol-shdc.exe
          - os: macos-latest
            suffix: mac
            exe: SyntonicDentiforms
            shdc_url: https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/osx/sokol-shdc
            shdc_out: tools/sokol-shdc
          - os: ubuntu-latest
            suffix: linux
            exe: SyntonicDentiforms
            shdc_url: https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/linux/sokol-shdc
            shdc_out: tools/sokol-shdc
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5
      - name: Download sokol-shdc
        shell: bash
        run: |
          curl -fL -o "${{ matrix.shdc_out }}" "${{ matrix.shdc_url }}"
          case "${{ runner.os }}" in
            Windows) ;;
            *) chmod +x "${{ matrix.shdc_out }}" ;;
          esac
      - name: Prepare Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
      - name: Configure and build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build --clean-first --config Debug
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --clean-first --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: SyntonicDentiforms-${{matrix.suffix}}
          path: |
            ${{matrix.exe}}
            readme.txt
            data/
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install-ninja
        run: |
          sudo apt-get update && sudo apt-get install -y ninja-build
      - name: prepare emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk
          cd emsdk
          ./emsdk install 5.0.5
          ./emsdk activate 5.0.5
          cd ..
      - name: Download sokol-shdc
        run: |
          URL="https://raw.githubusercontent.com/floooh/sokol-tools-bin/master/bin/linux/sokol-shdc"
          OUT="tools/sokol-shdc"
          curl -L -o "$OUT" "$URL"
          chmod +x "$OUT"      
      - name: build
        run: |
          source emsdk/emsdk_env.sh
          cmake --preset emscripten-release
          cmake --build --preset em-release
